name: Upload to Another Repository

on:
  push:
    branches:
      - main   # Trigger the pipeline on push to 'main' branch (or other branches as needed)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository (the one that triggers the action)
      - name: Checkout source repository
        uses: actions/checkout@v2

      # Step 2: Set up Git configuration for the target repository
      - name: Set up Git
        run: |
          git config --global user.name "pradeepgroot"
          git config --global user.email "pradeep.negi@grootsoftwares.com"

      # Step 3: Clone the target repository
      - name: Clone target repository
        run: |
          git clone https://github.com/pradeepgroot/schools.git target-repo
          
      # Step 4: Copy the code to the target repository
      - name: Copy files to target repository
        run: |
          cp -r ./tstSchoolTraget/* ./https://github.com/pradeepgroot/tst.git/
        
      # Step 5: Commit and push changes to the target repository
      - name: Commit and push to target repository
        run: |
          cd target-repo
          git add .
          git commit -m "Automated upload from source repository"
          git push https://github.com/pradeepgroot/schools.git main

      # Step 6: Optionally, clean up the cloned repository
      - name: Clean up
        run: |
          rm -rf target-repo
